-- =============================================================================
-- IT_HANDOVER: Run this script once against the production PostgreSQL database
-- after migrations have been applied. It creates a restricted application user
-- that has only the permissions needed to run the app — no DDL privileges.
--
-- Replace <APP_DB_PASSWORD> with a strong password generated by your secrets manager.
-- Update the DATABASE_URL in Railway / your vault to use app_user instead of the admin user.
-- =============================================================================

CREATE USER app_user WITH PASSWORD '<APP_DB_PASSWORD>';

GRANT CONNECT ON DATABASE workforce_planner TO app_user;
GRANT USAGE ON SCHEMA public TO app_user;

-- Allow app to read and write all current tables
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_user;

-- Ensure future tables created by migrations also get the right permissions
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO app_user;

-- DO NOT grant CREATE, DROP, ALTER, TRUNCATE or superuser to app_user.
-- Use the admin/migration user only for running schema migrations (e.g. via a CI job).
